### ISSUE TITLE
Python error on import photo

### ISSUE THREAD

**Issue by francoisatilio** [NaturalGIS/geotag_and_import_photos#13]
I get this error message 👍 
********************************************************************************************
2017-04-19T14:24:33	1	Traceback (most recent call last):
			  File "C:/Users/afrancois1/.qgis2/python/plugins\geotagphotos\importphotosdialog.py", line 88, in selectPhotosDir
			    self.loadTags(dirName)
			  File "C:/Users/afrancois1/.qgis2/python/plugins\geotagphotos\importphotosdialog.py", line 132, in loadTags
			    md = et.get_metadata(os.path.join(root, f))
			  File "C:/Users/afrancois1/.qgis2/python/plugins\geotagphotos\exiftool.py", line 255, in get_metadata
			    return self.execute_json(filename)[0]
			  File "C:/Users/afrancois1/.qgis2/python/plugins\geotagphotos\exiftool.py", line 239, in execute_json
			    return json.loads(self.execute(b"-j", *params).decode("utf-8"))
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\encodings\utf_8.py", line 16, in decode
			    return codecs.utf_8_decode(input, errors, True)
			UnicodeDecodeError: 'utf8' codec can't decode bytes in position 38052-38053: invalid continuation byte
*********************************************************************************************
when defining the path to this photo on import window
			
![dsc00850](https://cloud.githubusercontent.com/assets/8548708/25180068/da0c1292-250c-11e7-85e3-700f4d838dc7.JPG)

**Comment by gioman** [comment]
@francoisatilio try a path with no spaces, no special chars, etc.

**Comment by francoisatilio** [comment]
Done, but not work

I change the path to C:/Temp3 and I get the same message, finishing by

UnicodeDecodeError: 'utf8' codec can't decode bytes in position 
37994-37995: invalid continuation byte

It seems to be a problem with a tag, don't you think?

**Comment by gioman** [comment]
Sorry I can't investigate at the moment. Feel free to submit a patch if you find the bug.

**Comment by BillWilliamson** [comment]
Apologies, did not have ExifTool installed.
