### ISSUE TITLE
 QGIS 2.8.2: Error when choosing 'Settings' in Menu Bar on OsX

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/geotag_and_import_photos#7]
```
An error has occured while executing Python code:

Traceback (most recent call last): File "/Users/USERNAME_HERE/.qgis2/python/plugins/geotagphotos/geotagphotos.py", line 142, in settings dlg = settingsdialog.SettingsDialog(self.iface) File "/Users/USERNAME_HERE/.qgis2/python/plugins/geotagphotos/settingsdialog.py", line 49, in init self.manageGui() File "/Users/USERNAME_HERE/.qgis2/python/plugins/geotagphotos/settingsdialog.py", line 53, in manageGui self.leConfigPath.setText(utils.getConfigPath()) TypeError: QLineEdit.setText(QString): argument 1 has unexpected type 'QPyNullVariant'

Python version: 2.7.6 (default, Sep 9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
```

**Comment by jbogdani** [comment]
Any update on this issue? I'm not able to use the plugin at all....

**Comment by gioman** [comment]
> Any update on this issue? I'm not able to use the plugin at all....

Hi, no OsX here, and no one supporting bug fixing/further development at the moment. Cheers!
